name: Mark de Jong
description: Integer posuere erat a ante venenatis dapibus posuere velit aliquet.
url: http://www.markdejong.com
author:
  name: Mark de Jong
  title: Front-end Dev and Founder of Dapper &amp; some
  email: mark@markdejong.com
  bio: Nullam quis risus eget urna mollis ornare vel eu leo. Maecenas faucibus mollis interdum.
  avatar: img/assets/963783_10151409603996606_654139616_200x200.png
social:
  facebook: https://www.facebook.com/mark.dejong83
  twitter: https://www.twitter.com/mdejong83
generator: jekyll 1.4.3

source: app
destination: build
timezone: Europe/Amsterdam

# Markdown library
markdown: redcarpet
extensions: ['fenced_code_blocks', 'smart']
pygments: true

# Grunt handles images and assets.
exclude: ['node_modules', 'img', 'css', 'js', 'fonts',
          '**.png', '**.jpg', '**.jpeg', '**.gif', '**.webp', '**.svg', '**.ico']
include: ['.htaccess']

# _config.build.yml sets future and show_drafts to false on `grunt build`
future: true
show_drafts: true

permalink: /:year/:month/:day/:title.html
paginate: 5
paginate_path: 'page:num'
