# Site settings
title: Mark de Jong
email: mark@markdejong.com
description: "The Thoughts and Rants of a Typography Fanatic and Web Developer"
baseurl: ""
url: "http://markdejong.com"
paginate: 8

author:
  name: Mark de Jong
  title: Developer, Husband, Dutch-man and traveller
  email: mark@markdejong.com
  bio: Developer by day. Dreamer by night. Typography fanatic. Founder of <a href="http://dappersome.com">Dapper & some</a> web design

social:
  facebook: https://www.facebook.com/mark.dejong83
  twitter: https://www.twitter.com/mdejong83
  github: https://github.com/mistermark
  tumblr: http://ikheetmark.tumblr.com/
  flickr: https://www.flickr.com/people/markdejong/

navigation:
  - title: About
    url: /about.html
    permalink: /about/
  - title: Home
    url: /index.html
    permalink: /
  - title: Links
    url: /links.html
    permalink: /links/

collections:
  links:
    category: links


sass:
  sass_dir: _sass
  style: compressed

# Build settings
markdown: kramdown
permalink: pretty
